class CountryCodes {
  String countryName;
  String phoneCode;

  CountryCodes(this.countryName, this.phoneCode);
}

List<CountryCodes> countryCodes = [
  CountryCodes('Afghanistan', '+93'),
  CountryCodes('Albania', '+355'),
  CountryCodes('Algeria', '+213'),
  CountryCodes('American Samoa', '+1-684'),
  CountryCodes('Andorra', '+376'),
  CountryCodes('Angola', '+244'),
  CountryCodes('Anguilla', '+1-264'),
  CountryCodes('Antigua and Barbuda', '+1-268'),
  CountryCodes('Argentina', '+54'),
  CountryCodes('Armenia', '+374'),
  CountryCodes('Aruba', '+297'),
  CountryCodes('Australia', '+61'),
  CountryCodes('Austria', '+43'),
  CountryCodes('Azerbaijan', '+994'),
  CountryCodes('Bahamas', '+1-242'),
  CountryCodes('Bahrain', '+973'),
  CountryCodes('Bangladesh', '+880'),
  CountryCodes('Barbados', '+1-246'),
  CountryCodes('Belarus', '+375'),
  CountryCodes('Belgium', '+32'),
CountryCodes('Equatorial Guinea', '+240'),
CountryCodes('Eritrea', '+291'),
CountryCodes('Estonia', '+372'),
CountryCodes('Ethiopia', '+251'),
CountryCodes('Falkland Islands', '+500'),
CountryCodes('Faroe Islands', '+298'),
CountryCodes('Fiji', '+679'),
CountryCodes('Finland', '+358'),
CountryCodes('France', '+33'),
CountryCodes('French Polynesia', '+689'),
CountryCodes('Gabon', '+241'),
CountryCodes('Gambia', '+220'),
CountryCodes('Georgia', '+995'),
CountryCodes('Germany', '+49'),
CountryCodes('Ghana', '+233'),
CountryCodes('Gibraltar', '+350'),
CountryCodes('Greece', '+30'),
CountryCodes('Greenland', '+299'),
CountryCodes('Grenada', '+1-473'),
CountryCodes('Guam', '+1-671'),
CountryCodes('Guatemala', '+502'),
CountryCodes('Guernsey', '+44-1481'),
CountryCodes('Guinea', '+224'),
CountryCodes('Guinea-Bissau', '+245'),
CountryCodes('Guyana', '+592'),
CountryCodes('Haiti', '+509'),
CountryCodes('Honduras', '+504'),
CountryCodes('Hong Kong', '+852'),
CountryCodes('Hungary', '+36'),
CountryCodes('Iceland', '+354'),
CountryCodes('India', '+91'),
CountryCodes('Indonesia', '+62'),
CountryCodes('Iran', '+98'),
CountryCodes('Iraq', '+964'),
CountryCodes('Ireland', '+353'),
CountryCodes('Isle of Man', '+44-1624'),
CountryCodes('Israel', '+972'),
CountryCodes('Italy', '+39'),
CountryCodes('Ivory Coast', '+225'),
CountryCodes('Jamaica', '+1-876'),
CountryCodes('Japan', '+81'),
CountryCodes('Jersey', '+44-1534'),
CountryCodes('Jordan', '+962'),
CountryCodes('Kazakhstan', '+7'),
CountryCodes('Kenya', '+254'),
CountryCodes('Kiribati', '+686'),
CountryCodes('Kosovo', '+383'),
CountryCodes('Kuwait', '+965'),
CountryCodes('Kyrgyzstan', '+996'),
CountryCodes('Laos', '+856'),
CountryCodes('Latvia', '+371'),
CountryCodes('Lebanon', '+961'),
CountryCodes('Lesotho', '+266'),
CountryCodes('Liberia', '+231'),
CountryCodes('Libya', '+218'),
CountryCodes('Liechtenstein', '+423'),
CountryCodes('Lithuania', '+370'),
CountryCodes('Luxembourg', '+352'),
CountryCodes('Macau', '+853'),
CountryCodes('Macedonia', '+389'),
CountryCodes('Madagascar', '+261'),
CountryCodes('Malawi', '+265'),
CountryCodes('Malaysia', '+60'),
CountryCodes('Maldives', '+960'),
CountryCodes('Mali', '+223'),
CountryCodes('Malta', '+356'),
CountryCodes('Marshall Islands', '+692'),
CountryCodes('Mauritania', '+222'),
CountryCodes('Mauritius', '+230'),
CountryCodes('Mayotte', '+262'),
CountryCodes('Mexico', '+52'),
  CountryCodes('Micronesia', '+691'),
  CountryCodes('Moldova', '+373'),
  CountryCodes('Monaco', '+377'),
  CountryCodes('Mongolia', '+976'),
  CountryCodes('Montenegro', '+382'),
  CountryCodes('Montserrat', '+1-664'),
  CountryCodes('Morocco', '+212'),
  CountryCodes('Mozambique', '+258'),
  CountryCodes('Myanmar', '+95'),
  CountryCodes('Namibia', '+264'),
  CountryCodes('Nauru', '+674'),
  CountryCodes('Nepal', '+977'),
  CountryCodes('Netherlands', '+31'),
  CountryCodes('Netherlands Antilles', '+599'),
  CountryCodes('New Caledonia', '+687'),
  CountryCodes('New Zealand', '+64'),
  CountryCodes('Nicaragua', '+505'),
  CountryCodes('Niger', '+227'),
  CountryCodes('Nigeria', '+234'),
  CountryCodes('Niue', '+683'),
  CountryCodes('Norfolk Island', '+672'),
  CountryCodes('North Korea', '+850'),
  CountryCodes('Northern Mariana Islands', '+1-670'),
  CountryCodes('Norway', '+47'),
  CountryCodes('Oman', '+968'),
  CountryCodes('Pakistan', '+92'),
  CountryCodes('Palau', '+680'),
  CountryCodes('Palestine', '+970'),
  CountryCodes('Panama', '+507'),
  CountryCodes('Papua New Guinea', '+675'),
  CountryCodes('Paraguay', '+595'),
  CountryCodes('Peru', '+51'),
  CountryCodes('Philippines', '+63'),
  CountryCodes('Pitcairn', '+64'),
  CountryCodes('Poland', '+48'),
  CountryCodes('Portugal', '+351'),
  CountryCodes('Puerto Rico', '+1-787, 1-939'),
  CountryCodes('Qatar', '+974'),
  CountryCodes('Republic of the Congo', '+242'),
  CountryCodes('Reunion', '+262'),
  CountryCodes('Romania', '+40'),
  CountryCodes('Russia', '+7'),
  CountryCodes('Rwanda', '+250'),
  CountryCodes('Saint Barthelemy', '+590'),
  CountryCodes('Saint Helena', '+290'),
  CountryCodes('Saint Kitts and Nevis', '+1-869'),
  CountryCodes('Saint Lucia', '+1-758'),
  CountryCodes('Saint Martin', '+590'),
  CountryCodes('Saint Pierre and Miquelon', '+508'),
  CountryCodes('Saint Vincent and the Grenadines', '+1-784'),
  CountryCodes('Samoa', '+685'),
  CountryCodes('San Marino', '+378'),
  CountryCodes('Sao Tome and Principe', '+239'),
  CountryCodes('Saudi Arabia', '+966'),
  CountryCodes('Senegal', '+221'),
  CountryCodes('Serbia', '+381'),
  CountryCodes('Seychelles', '+248'),
  CountryCodes('Sierra Leone', '+232'),
  CountryCodes('Singapore', '+65'),
  CountryCodes('Sint Maarten', '+1-721'),
  CountryCodes('Slovakia', '+421'),
  CountryCodes('Slovenia', '+386'),
  CountryCodes('Solomon Islands', '+677'),
  CountryCodes('Somalia', '+252'),
  CountryCodes('South Africa', '+27'),
  CountryCodes('South Korea', '+82'),
  CountryCodes('South Sudan', '+211'),
  CountryCodes('Spain', '+34'),
  CountryCodes('Sudan', '+249'),
  CountryCodes('Suriname', '+597'),
  CountryCodes('Svalbard and Jan Mayen', '+47'),
  CountryCodes('Swaziland', '+268'),
  CountryCodes('Sweden', '+46'),
  CountryCodes('Switzerland', '+41'),
  CountryCodes('Syria', '+963'),
  CountryCodes('Taiwan', '+886'),
  CountryCodes('Tajikistan', '+992'),
  CountryCodes('Tanzania', '+255'),
  CountryCodes('Thailand', '+66'),
  CountryCodes('Togo', '+228'),
  CountryCodes('Tokelau', '+690'),
  CountryCodes('Tonga', '+676'),
  CountryCodes('Trinidad and Tobago', '+1-868'),
  CountryCodes('Tunisia', '+216'),
  CountryCodes('Turkey', '+90'),
  CountryCodes('Turkmenistan', '+993'),
  CountryCodes('Turks and Caicos Islands', '+1-649'),
  CountryCodes('Tuvalu', '+688'),
  CountryCodes('U.S. Virgin Islands', '+1-340'),
  CountryCodes('Uganda', '+256'),
  CountryCodes('Ukraine', '+380'),
  CountryCodes('United Arab Emirates', '+971'),
  CountryCodes('United Kingdom', '+44'),
  CountryCodes('United States', '+1'),
  CountryCodes('Uruguay', '+598'),
  CountryCodes('Uzbekistan', '+998'),
  CountryCodes('Vanuatu', '+678'),
  CountryCodes('Vatican', '+379'),
  CountryCodes('Venezuela', '+58'),
  CountryCodes('Vietnam', '+84'),
  CountryCodes('Wallis and Futuna', '+681'),
  CountryCodes('Western Sahara', '+212'),
  CountryCodes('Yemen', '+967'),
  CountryCodes('Zambia', '+260'),
  CountryCodes('Zimbabwe', '+263'),

];